apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookverse-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nagarajuv-jfrog/hc-bookverse-gitops-config.git'
    targetRevision: HEAD
    path: helm/bookverse
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hc-bookverse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
