# This is a simplified manifest. In a real scenario, you would have
# separate files and more complex configurations.
# We are using placeholder images here as the actual image tags
# would be dynamically resolved by a more advanced GitOps process.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-frontend
spec:
  replicas: 1
  selector: { matchLabels: { app: inventory-frontend } }
  template:
    metadata: { labels: { app: inventory-frontend } }
    spec:
      containers:
      - name: inventory-frontend
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-frontend-svc
spec:
  type: NodePort
  selector:
    app: inventory-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
---
apiVersion:: apps/v1
kind: Deployment
metadata:
  name: inventory-backend
spec:
  replicas: 1
  selector: { matchLabels: { app: inventory-backend } }
  template:
    metadata: { labels: { app: inventory-backend } }
    spec:
      containers:
      - name: inventory-backend
        image: python:3.9-slim
        command: ["sleep", "3600"]