{{- range $name, $vals := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}-frontend
  template:
    metadata:
      labels:
        app: {{ $name }}-frontend
      annotations:
        rollme: {{ $.Values.restart_timestamp | quote }}
    spec:
      # This tells the deployment to use our secret for pulling images
      imagePullSecrets:
      - name: jfrog-registry-creds
      containers:
      - name: {{ $name }}-frontend
        image: {{ $vals.frontend.image }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-frontend-svc
spec:
  type: NodePort
  selector:
    app: {{ $name }}-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ $vals.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}-backend
  template:
    metadata:
      labels:
        app: {{ $name }}-backend
      annotations:
        rollme: {{ $.Values.restart_timestamp | quote }}
    spec:
      # This tells the deployment to use our secret for pulling images
      imagePullSecrets:
      - name: jfrog-registry-creds
      containers:
      - name: {{ $name }}-backend
        image: {{ $vals.backend.image }}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-backend-svc
spec:
  type: ClusterIP
  selector:
    # This selector correctly targets the backend pods.
    app: {{ $name }}-backend
  ports:
  - port: 5000
    targetPort: 5000
{{- end }}
