name: 'Promotion to Commit'
on:
  repository_dispatch:
    types: [rlm_promotion]
jobs:
  update-gitops-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v3
      - name: Extract Bundle Version from Webhook
        id: get_version
        run: echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
      - name: Update values.yaml
        run: |
          sed -i "s/solutionBundleVersion:.*/solutionBundleVersion: \"${{ env.VERSION }}\"/" helm/bookverse/values.yaml
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Promoting ${{ env.VERSION }} to production"
          git push
