name: 'Promotion to Commit'
on:
  repository_dispatch:
    types: [rlm_promotion]
jobs:
  update-gitops-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v3

      - name: Install jq and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Get Promoted Bundle Info from Webhook
        id: get_info
        run: |
          echo "BUNDLE_NAME=${{ github.event.client_payload.name }}" >> $GITHUB_ENV
          echo "BUNDLE_VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV

      - name: Update Image Tags in values.yaml
        run: |
          # Use a direct API call to get the platform bundle contents
          PLATFORM_BUNDLE_CONTENTS=$(curl -H "Authorization: Bearer ${{ secrets.JFROG_ACCESS_TOKEN }}" "${{ vars.JFROG_URL }}/lifecycle/api/v2/release_bundles/${{ env.BUNDLE_NAME }}/${{ env.BUNDLE_VERSION }}?project=bookverse")
          echo "Platform Bundle Contents: $PLATFORM_BUNDLE_CONTENTS"

          # Loop through each source microservice bundle within the platform bundle
          for service_bundle in $(echo "${PLATFORM_BUNDLE_CONTENTS}" | jq -r '.source.release_bundles[]'); do
            SERVICE_BUNDLE_NAME=$(echo "$service_bundle" | jq -r '.release_bundle_name')
            SERVICE_VERSION=$(echo "$service_bundle" | jq -r '.release_bundle_version')

            # This is a key fix: strip '-service' from the bundle name to match the key in values.yaml
            SERVICE_KEY=$(echo "$SERVICE_BUNDLE_NAME" | sed 's/-service//')

            echo "Processing microservice: $SERVICE_BUNDLE_NAME (key: $SERVICE_KEY) version $SERVICE_VERSION"

            # Get the contents of the microservice bundle to find the actual Docker images
            SERVICE_CONTENTS=$(curl -H "Authorization: Bearer ${{ secrets.JFROG_ACCESS_TOKEN }}" "${{ vars.JFROG_URL }}/lifecycle/api/v2/release_bundles/${SERVICE_BUNDLE_NAME}/${SERVICE_VERSION}?project=bookverse")
            echo "Service Contents: $SERVICE_CONTENTS"

            # Extract the frontend and backend image tags
            FRONTEND_IMAGE=$(echo "${SERVICE_CONTENTS}" | jq -r '.source.artifacts[] | select(.path | contains("frontend")) | .path')
            BACKEND_IMAGE=$(echo "${SERVICE_CONTENTS}" | jq -r '.source.artifacts[] | select(.path | contains("backend")) | .path')

            # The path includes the repo, so we need to add the registry URL
            REGISTRY_URL=$(echo "${{ vars.JFROG_URL }}" | sed 's|https://||')
            FULL_FRONTEND_IMAGE="$REGISTRY_URL/$FRONTEND_IMAGE"
            FULL_BACKEND_IMAGE="$REGISTRY_URL/$BACKEND_IMAGE"

            echo "Updating frontend image for $SERVICE_KEY to $FULL_FRONTEND_IMAGE"
            yq e -i ".services.$SERVICE_KEY.frontend.image = \"$FULL_FRONTEND_IMAGE\"" helm/bookverse/values.yaml

            echo "Updating backend image for $SERVICE_KEY to $FULL_BACKEND_IMAGE"
            yq e -i ".services.$SERVICE_KEY.backend.image = \"$FULL_BACKEND_IMAGE\"" helm/bookverse/values.yaml
          done

          echo "Final values.yaml content:"
          cat helm/bookverse/values.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add helm/bookverse/values.yaml
          git commit -m "Promoting ${{ env.BUNDLE_NAME }} ${{ env.BUNDLE_VERSION }} to production"
          git push
          