name: 'Promote Platform Bundle to PROD'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the bookverse-platform release bundle to promote (e.g., 4.0.1)'
        required: true
        default: '1.0.'
run-name: Promote ${{ github.event.inputs.bundle_name }} v${{ github.event.inputs.bundle_ver }} to PROD

jobs:
  promote-sequentially:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_URL }}
          JF_USER: ${{ vars.JFROG_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
          JF_PROJECT: "bookverse"

      - name: Promote to DEV
        run: |
          echo "Promoting bookverse-platform version ${{ github.event.inputs.version }} to DEV..."
          jfrog rbp bookverse-platform ${{ github.event.inputs.version }} DEV \
            --project=bookverse \
            --include-repos='bookverse-docker-external' \
            --promotion-type=move

#      - name: Promote to QA
#        run: |
#          echo "Promoting bookverse-platform version ${{ github.event.inputs.version }} to QA..."
#          jfrog rbp bookverse-platform ${{ github.event.inputs.version }} QA \
#            --project=bookverse \
#            --include-repos='bookverse-docker-external' \
#            --promotion-type=move

 #     - name: Promote to STAGE
 #       run: |
 #         echo "Promoting bookverse-platform version ${{ github.event.inputs.version }} to STAGE..."
 #         jfrog rbp bookverse-platform ${{ github.event.inputs.version }} STAGE \
 #           --project=bookverse \
 #           --include-repos='bookverse-docker-external' \
 #           --promotion-type=move

      - name: Promote to PROD
        run: |
          echo "Promoting bookverse-platform version ${{ github.event.inputs.version }} to PROD..."
          jfrog rbp bookverse-platform ${{ github.event.inputs.version }} PROD \
            --project=bookverse \
            --include-repos='bookverse-docker-external-prod' \
            --promotion-type=move